# Generated by Django 2.0.13 on 2019-08-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GruposPermisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('gestionar_grupos', 'Gestión de grupos de usuarios'),),
                'managed': False,
            },
        ),
    ]
