# Generated by Django 2.0.13 on 2019-08-06 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0002_auto_20190806_0326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='nombre del producto*')),
                ('unidad_medida', models.CharField(max_length=50, verbose_name='unidad de medida*')),
                ('precio', models.PositiveIntegerField(verbose_name='precio de venta*')),
                ('cantidad', models.PositiveIntegerField(verbose_name='cantidad actual*')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('imagen', models.ImageField(blank=True, upload_to='crear_ruta_medicamento', verbose_name='imagen del producto')),
                ('activo', models.BooleanField(default=True, verbose_name='¿El producto está activo actualmente?')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='categorias.Categoria', verbose_name='categoría del producto*')),
            ],
            options={
                'ordering': ['nombre'],
                'permissions': (('gestionar_productos', 'Gestión de productos'),),
            },
        ),
    ]
