# Generated by Django 2.0.13 on 2019-07-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=50, verbose_name='Referencia ')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre ')),
                ('activo', models.BooleanField(default=True, verbose_name='¿El medicamento está activo actualmente?')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
