# Generated by Django 2.0.13 on 2019-08-09 05:05

import apps.medicamentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=apps.medicamentos.models.crear_ruta_medicamento, verbose_name='imagen del producto'),
        ),
    ]
