# Generated by Django 2.0.13 on 2019-08-06 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicamento',
            options={'ordering': ['nombre'], 'permissions': (('gestionar_productos', 'Gestión de productos'),)},
        ),
    ]
