# Generated by Django 2.0.13 on 2019-08-05 08:41

import apps.empresas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20190805_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, upload_to=apps.empresas.models.crear_ruta_logo, verbose_name='logo del negocio'),
        ),
    ]
