# Generated by Django 2.0.13 on 2019-07-19 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(blank=True, choices=[('Mujer', 'Mujer'), ('Hombre', 'Hombre'), ('Otro', 'Otro')], max_length=20, verbose_name='género')),
                ('acepto_terminos_condiciones', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('Cédula de ciudadanía', 'Cédula de ciudadanía'), ('Cédula de extranjería', 'Cédula de extranjería'), ('Tarjeta de identidad', 'Tarjeta de identidad'), ('Pasaporte', 'Pasaporte')], max_length=50, verbose_name='tipo de documento de identidad*')),
                ('numero_documento', models.CharField(max_length=50, verbose_name='número de documento de identidad*')),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha de nacimiento*')),
                ('genero', models.CharField(choices=[('Mujer', 'Mujer'), ('Hombre', 'Hombre'), ('Otro', 'Otro')], max_length=20, verbose_name='género*')),
                ('celular', models.CharField(max_length=25, verbose_name='número de celular*')),
            ],
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['first_name', 'last_name'], 'permissions': (('gestionar_usuarios', 'Gestión de usuarios'),)},
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Trabajador', 'Trabajador')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_trabajador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_cliente', to=settings.AUTH_USER_MODEL),
        ),
    ]
