# Generated by Django 2.0.13 on 2019-08-06 06:27

import apps.usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20190719_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=apps.usuarios.models.crear_ruta_trabajador, verbose_name='imagen del trabajador'),
        ),
    ]
