# Generated by Django 2.0.5 on 2019-03-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogActualizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('duracion', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='LogApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.TextField()),
                ('usuario', models.CharField(max_length=150)),
                ('grupo_usuario', models.CharField(max_length=150)),
                ('fecha_log', models.DateField(auto_now=True, verbose_name='timestamp')),
                ('hora_log', models.TimeField(auto_now=True, verbose_name='timestamp')),
                ('ip_cliente', models.CharField(max_length=50)),
                ('peticion', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], max_length=50)),
            ],
        ),
    ]
