# Generated by Django 2.0.13 on 2019-08-25 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20190825_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compras_del_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venta',
            name='trabajador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_del_trabajador', to=settings.AUTH_USER_MODEL),
        ),
    ]
