# Generated by Django 2.0.13 on 2019-08-06 08:26

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ejemplo: Vitaminas', max_length=50, unique=True, verbose_name='nombre de la categoría de productos*')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción (opcional)')),
            ],
            options={
                'ordering': ['nombre'],
                'permissions': (('gestionar_categorias', 'Gestión de categorias'),),
            },
        ),
        migrations.CreateModel(
            name='HistoricalCategoria',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, help_text='Ejemplo: Vitaminas', max_length=50, verbose_name='nombre de la categoría de productos*')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción (opcional)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('empresa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empresas.Empresa')),
            ],
            options={
                'verbose_name': 'historical categoria',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
