# Generated by Django 2.0.13 on 2019-08-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_auto_20190806_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿La categoría está activa actualmente?'),
        ),
        migrations.AddField(
            model_name='historicalcategoria',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿La categoría está activa actualmente?'),
        ),
    ]
